name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag victorgrubio/ecommerce-frontend-angular:1.0.0
    - name: Push the docker image
      run: docker push victorgrubio/ecommerce-frontend-angular:1.0.0
